name: http_middleware
description: Library that allows simple composition of HTTP interactions.
version: 0.0.1
author: kyuqw
homepage: 'https://github.com/kyuqw/http_middleware'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
